(() => {
  const channels = [
    {ch:1,  name:"TVF Originals",  cat:"OTT",    lang:"Hindi",  handle:"TheViralFever",    desc:"Panchayat, Kota Factory, Aspirants & more"},
    {ch:2,  name:"Dice Media",     cat:"OTT",    lang:"Hindi",  handle:"DiceMediaIndia",   desc:"Little Things, Operation MBBS & more"},
    {ch:3,  name:"Girliyapa",      cat:"OTT",    lang:"Hindi",  handle:"Girliyapa",        desc:"TVF's women-led comedy channel"},
    {ch:4,  name:"Sony SET India", cat:"OTT",    lang:"Hindi",  handle:"setindia",         desc:"CID, Taarak Mehta, KBC full episodes"},
    {ch:5,  name:"SonyLIV",        cat:"OTT",    lang:"Hindi",  handle:"SonyLIV",          desc:"Scam 1992, Rocket Boys, Gullak"},
    {ch:6,  name:"MX Player",      cat:"OTT",    lang:"Hindi",  handle:"MXPlayerOfficial", desc:"Aashram, Raktanchal, Campus Diaries"},
    {ch:7,  name:"Amazon miniTV",  cat:"OTT",    lang:"Hindi",  handle:"amazonminitv",     desc:"Free originals & short films"},
    {ch:8,  name:"Zee5",           cat:"OTT",    lang:"Hindi",  handle:"ZEE5",             desc:"Zee5 originals & shows"},
    {ch:9,  name:"Stage",          cat:"OTT",    lang:"Hindi",  handle:"StageApp",         desc:"Stand-up, sketches & originals"},
    {ch:10, name:"FilterCopy",     cat:"Comedy", lang:"Hindi",  handle:"FilterCopy",       desc:"Relatable sketches & short films"},
    {ch:11, name:"BB Ki Vines",    cat:"Comedy", lang:"Hindi",  handle:"BBKiVines",        desc:"Bhuvan Bam's comedy universe"},
    {ch:12, name:"Round2Hell",     cat:"Comedy", lang:"Hindi",  handle:"Round2hell",       desc:"Sketch comedy & viral videos"},
    {ch:13, name:"Comicstaan",     cat:"Comedy", lang:"Hindi",  handle:"Comicstaan",       desc:"Stand-up comedy from Amazon"},
    {ch:14, name:"Zakir Khan",     cat:"Comedy", lang:"Hindi",  handle:"zakirkhan",        desc:"Sakht launda stand-up & vlogs"},
    {ch:15, name:"Shemaroo",       cat:"Movies", lang:"Hindi",  handle:"ShemarooMe",       desc:"Full Bollywood movies & scenes free"},
    {ch:16, name:"YRF Movies",     cat:"Movies", lang:"Hindi",  handle:"YRFMovies",        desc:"Yash Raj Films - full movies & songs"},
    {ch:17, name:"Allu Arjun",     cat:"Movies", lang:"Telugu", handle:"AlluArjun",        desc:"Pushpa, Ala Vaikunthapurramuloo clips"},
    {ch:18, name:"ABP Studios",    cat:"OTT",    lang:"Hindi",  handle:"ABPStudios",       desc:"ABP originals & web series"},
    {ch:19, name:"Mahabharat",     cat:"OTT",    lang:"Hindi",  handle:"PenBhakti",        desc:"BR Chopra's Mahabharat - all episodes"},
    {ch:20, name:"Devon Ke Dev Mahadev", cat:"OTT", lang:"Hindi", playlistId:"PLtW7SFqfLw4-4L_LpLuXSgOfQE5KH3X4B", desc:"247 episodes"},
    {ch:21, name:"Hotstar",      cat:"OTT",   lang:"Hindi", url:"https://www.hotstar.com", desc:"Disney+ Hotstar"},
    {ch:22, name:"SonyLIV App",  cat:"OTT",   lang:"Hindi", url:"https://www.sonyliv.com", desc:"SonyLIV streaming"},
    {ch:23, name:"Prime Video",  cat:"OTT",   lang:"Hindi", url:"https://www.primevideo.com", desc:"Amazon Prime Video"},
    {ch:24, name:"Kuku FM",      cat:"OTT",   lang:"Hindi", url:"https://www.kukufm.com", desc:"Audio stories & podcasts"},
  ];

  let currentIndex = 0;
  let bannerTimeout = null;
  let numberBuffer = '';
  let numberTimeout = null;
  let guideOpen = false;
  let activeFilter = 'All';
  let ytPlayer = null;
  let ytReady = false;
  let videoDb = {}; // handle -> [videoIds]
  let errorCount = 0;
  const MAX_ERRORS = 5;
  let skipAttempts = 0;
  const MAX_SKIP = 24;
  let shuffleMode = false; // default: sequential

  const $ = id => document.getElementById(id);
  const banner = $('channel-banner');
  const staticOverlay = $('static-overlay');
  const staticCanvas = $('static-canvas');
  const guide = $('guide');
  const numberInput = $('number-input');
  const numberDisplay = $('number-display');
  const errorOverlay = $('error-overlay');

  // Load video database (pre-generated by GitHub Actions)
  fetch('videos.json')
    .then(r => r.json())
    .then(data => {
      videoDb = data;
      console.log('Loaded video database:', Object.keys(data).length, 'channels');
    })
    .catch(e => console.error('Failed to load videos.json:', e));

  // Load YouTube IFrame API
  const tag = document.createElement('script');
  tag.src = 'https://www.youtube.com/iframe_api';
  document.head.appendChild(tag);

  window.onYouTubeIframeAPIReady = function () {
    ytPlayer = new YT.Player('yt-player', {
      width: '100%',
      height: '100%',
      playerVars: {
        autoplay: 1,
        controls: 1,
        disablekb: 0,
        fs: 1,
        iv_load_policy: 3,
        modestbranding: 1,
        rel: 0,
        playsinline: 1,
        origin: window.location.origin,
      },
      events: {
        onReady: onPlayerReady,
        onStateChange: onPlayerStateChange,
        onError: onPlayerError,
      },
    });
  };

  function onPlayerReady() {
    ytReady = true;
    ytPlayer.mute();
    $('btn-mute').textContent = 'UNMUTE';
    updateShuffleBtn();
    buildGuide();
    // Restore last channel (e.g. after returning from Hotstar via back button)
    let startCh = 0;
    try {
      const saved = localStorage.getItem('ott_last_channel');
      if (saved !== null) startCh = parseInt(saved, 10) || 0;
    } catch(e) {}
    tuneToChannel(startCh);
  }

  // --- Progress save/restore (all channels) ---
  function getProgress(ch) {
    try {
      const key = 'ott_progress_' + (ch.playlistId || ch.handle);
      return JSON.parse(localStorage.getItem(key) || '{}');
    } catch (e) { return {}; }
  }

  function saveProgress(ch, index, time) {
    try {
      const key = 'ott_progress_' + (ch.playlistId || ch.handle);
      localStorage.setItem(key, JSON.stringify({ index: index, time: Math.floor(time) }));
    } catch (e) {}
  }

  let saveInterval = null;
  function startSaving() {
    stopSaving();
    saveInterval = setInterval(() => {
      if (!ytPlayer) return;
      const ch = channels[currentIndex];
      if (!ch) return;
      try {
        const state = ytPlayer.getPlayerState();
        if (state === YT.PlayerState.PLAYING || state === YT.PlayerState.PAUSED) {
          const idx = ytPlayer.getPlaylistIndex();
          const time = ytPlayer.getCurrentTime();
          if (idx >= 0 && time > 0) saveProgress(ch, idx, time);
        }
      } catch (e) {}
    }, 5000);
  }

  function stopSaving() {
    if (saveInterval) { clearInterval(saveInterval); saveInterval = null; }
  }

  // --- Tuning ---
  let tuneSeq = 0;
  let switchDebounce = null;

  function tuneToChannel(index) {
    if (!channels.length) return;
    index = ((index % channels.length) + channels.length) % channels.length;
    currentIndex = index;
    const ch = channels[index];
    const seq = ++tuneSeq;
    errorCount = 0;

    hideError();
    showBanner(ch);
    showStatic();
    updateGuideActive();
    try { localStorage.setItem('ott_last_channel', index); } catch(e) {}

    clearTimeout(switchDebounce);
    switchDebounce = setTimeout(() => {
      if (seq !== tuneSeq) return;
      loadChannel(ch, seq);
    }, 200);
  }

  function loadChannel(ch, seq) {
    if (!ytReady || !ytPlayer) return;
    stopSaving();

    // URL-based channel
    if (ch.url) {
      hideStatic();
      if (window.OttApp) {
        // Android app — show in overlay WebView, controls stay active
        window.OttApp.showUrl(ch.url);
      } else {
        // Web browser — show overlay with open button
        showUrlOverlay(ch);
      }
      return;
    }
    // Hide overlay when switching to non-URL channel
    if (window.OttApp) window.OttApp.hideUrl();
    hideUrlOverlay();

    // Playlist-based channel (e.g., DKDM) — use YouTube playlist directly
    if (ch.playlistId) {
      const progress = shuffleMode ? {} : getProgress(ch);
      ytPlayer.loadPlaylist({
        list: ch.playlistId,
        listType: 'playlist',
        index: progress.index || 0,
        startSeconds: progress.time || 0,
      });
      if (shuffleMode) {
        setTimeout(() => { try { ytPlayer.setShuffle(true); } catch(e){} }, 1000);
      }
      startSaving();
      waitForPlayback(seq);
      return;
    }

    // Video ID-based channel (from videos.json)
    const videos = videoDb[ch.handle] || [];

    if (videos.length === 0) {
      skipAttempts++;
      if (skipAttempts < MAX_SKIP) {
        tuneToChannel(currentIndex + 1);
      } else {
        hideStatic();
        showError(ch.name);
      }
      return;
    }
    skipAttempts = 0;

    let playlist;
    if (shuffleMode) {
      playlist = [...videos].sort(() => Math.random() - 0.5);
    } else {
      playlist = [...videos];
    }

    const progress = shuffleMode ? {} : getProgress(ch);
    const startIdx = progress.index || 0;

    // Play first video immediately for fast start
    ytPlayer.loadVideoById({ videoId: playlist[startIdx] || playlist[0], startSeconds: progress.time || 0 });

    // After playback starts, load full playlist for continuous play
    let playlistLoaded = false;
    const checkPlaying = setInterval(() => {
      if (seq !== tuneSeq) { clearInterval(checkPlaying); return; }
      try {
        if (ytPlayer.getPlayerState() === YT.PlayerState.PLAYING) {
          clearInterval(checkPlaying);
          hideStatic();
          if (!playlistLoaded && playlist.length > 1) {
            playlistLoaded = true;
            setTimeout(() => {
              if (seq !== tuneSeq) return;
              ytPlayer.loadPlaylist(playlist, startIdx, progress.time || 0);
            }, 2000);
          }
        }
      } catch (e) {}
    }, 200);

    startSaving();

    // Timeout — hide static after 6s
    setTimeout(() => {
      clearInterval(checkPlaying);
      if (seq !== tuneSeq) return;
      hideStatic();
      try {
        if (ytPlayer.getPlayerState() !== YT.PlayerState.PLAYING) ytPlayer.playVideo();
      } catch (e) {}
    }, 6000);
  }

  function waitForPlayback(seq) {
    const checkPlaying = setInterval(() => {
      if (seq !== tuneSeq) { clearInterval(checkPlaying); return; }
      try {
        if (ytPlayer.getPlayerState() === YT.PlayerState.PLAYING) {
          clearInterval(checkPlaying);
          hideStatic();
          skipAttempts = 0;
        }
      } catch (e) {}
    }, 300);

    setTimeout(() => {
      clearInterval(checkPlaying);
      if (seq !== tuneSeq) return;
      hideStatic();
      try { if (ytPlayer.getPlayerState() !== YT.PlayerState.PLAYING) ytPlayer.playVideo(); } catch (e) {}
    }, 8000);
  }

  function onPlayerStateChange(event) {
    if (event.data === YT.PlayerState.PLAYING) {
      hideStatic();
      hideError();
      errorCount = 0;
    }
    if (event.data === YT.PlayerState.ENDED) {
      ytPlayer.nextVideo();
    }
  }

  function onPlayerError(event) {
    errorCount++;
    if (errorCount < MAX_ERRORS && ytPlayer) {
      ytPlayer.nextVideo();
    } else {
      skipAttempts++;
      if (skipAttempts < MAX_SKIP) {
        tuneToChannel(currentIndex + 1);
      } else {
        hideStatic();
        const ch = channels[currentIndex];
        if (ch) showError(ch.name + ' (videos blocked)');
      }
    }
  }

  // --- Shuffle toggle ---
  function toggleShuffle() {
    shuffleMode = !shuffleMode;
    updateShuffleBtn();
    // Reload current channel with new mode
    tuneToChannel(currentIndex);
  }

  function updateShuffleBtn() {
    const btn = $('btn-shuffle');
    if (btn) btn.textContent = shuffleMode ? 'SEQUENTIAL' : 'SHUFFLE';
  }

  // --- Banner ---
  function showBanner(ch) {
    $('banner-number').textContent = ch.ch;
    $('banner-name').textContent = ch.name;
    let desc = ch.desc || '';
    if (!shuffleMode) {
      const progress = getProgress(ch);
      if (progress.index > 0) desc = 'Resuming from #' + (progress.index + 1);
    } else {
      desc = (ch.desc || '') + ' (shuffle)';
    }
    $('banner-desc').textContent = desc;
    $('banner-meta').textContent = ch.lang + ' \u2022 ' + ch.cat;
    $('banner-category').textContent = ch.cat;
    banner.classList.remove('hidden', 'hiding');
    clearTimeout(bannerTimeout);
    bannerTimeout = setTimeout(() => {
      banner.classList.add('hiding');
      setTimeout(() => banner.classList.add('hidden'), 300);
    }, 4000);
  }

  function showError(name) { errorOverlay.classList.remove('hidden'); $('error-channel-name').textContent = name; }
  function hideError() { errorOverlay.classList.add('hidden'); }

  function showUrlOverlay(ch) {
    let overlay = $('url-overlay');
    if (!overlay) {
      overlay = document.createElement('div');
      overlay.id = 'url-overlay';
      overlay.style.cssText = 'position:absolute;inset:0;z-index:4;display:flex;align-items:center;justify-content:center;background:radial-gradient(ellipse at center,#0a1a2e 0%,#000 70%)';
      $('app').appendChild(overlay);
    }
    overlay.innerHTML =
      '<div style="text-align:center;padding:20px">' +
        '<div style="font-size:32px;font-weight:700;margin-bottom:8px">' + ch.name + '</div>' +
        '<div style="font-size:15px;color:#888;margin-bottom:30px">' + (ch.desc || '') + '</div>' +
        '<a href="' + ch.url + '" target="_blank" rel="noopener" style="display:inline-block;padding:16px 40px;background:#e50914;color:#fff;font-size:18px;font-weight:700;text-decoration:none;border-radius:8px">OPEN ' + ch.name.toUpperCase() + '</a>' +
        '<div style="font-size:12px;color:#555;margin-top:20px">Opens in new tab. Use CH+/CH- to switch channels.</div>' +
      '</div>';
    overlay.classList.remove('hidden');
  }

  function hideUrlOverlay() {
    const overlay = $('url-overlay');
    if (overlay) overlay.classList.add('hidden');
  }

  function showStatic() { staticOverlay.classList.remove('hidden'); drawStatic(); }
  function hideStatic() { staticOverlay.classList.add('hidden'); }

  function drawStatic() {
    const ctx = staticCanvas.getContext('2d');
    const w = staticCanvas.width = 320;
    const h = staticCanvas.height = 240;
    function frame() {
      if (staticOverlay.classList.contains('hidden')) return;
      const imageData = ctx.createImageData(w, h);
      const buf = new Uint32Array(imageData.data.buffer);
      for (let i = 0; i < buf.length; i++) {
        const v = (Math.random() * 255) | 0;
        buf[i] = 0xFF000000 | (v << 16) | (v << 8) | v;
      }
      ctx.putImageData(imageData, 0, 0);
      requestAnimationFrame(frame);
    }
    frame();
  }

  // --- Navigation ---
  function nextChannel() { tuneToChannel(currentIndex + 1); }
  function prevChannel() { tuneToChannel(currentIndex - 1); }
  function goToChannelNumber(num) {
    const idx = channels.findIndex(c => c.ch === num);
    if (idx !== -1) tuneToChannel(idx);
  }

  function handleNumber(digit) {
    numberBuffer += digit;
    numberDisplay.textContent = numberBuffer;
    numberInput.classList.remove('hidden');
    clearTimeout(numberTimeout);
    numberTimeout = setTimeout(() => {
      const num = parseInt(numberBuffer, 10);
      numberBuffer = '';
      numberInput.classList.add('hidden');
      if (num >= 1 && num <= channels.length) goToChannelNumber(num);
    }, 1200);
  }

  // Expose for Android native controls
  window.handleAndroidBack = function() {
    if (guideOpen) { toggleGuide(); return true; }
    return false;
  };
  window.channelUp = function() { prevChannel(); };
  window.channelDown = function() { nextChannel(); };

  // --- Guide ---
  function buildGuide() {
    const list = $('guide-list');
    list.innerHTML = '';
    const filtered = activeFilter === 'All' ? channels : channels.filter(c => c.cat === activeFilter);
    filtered.forEach(ch => {
      const i = channels.indexOf(ch);
      const progress = getProgress(ch);
      const item = document.createElement('div');
      item.className = 'guide-item' + (i === currentIndex ? ' active' : '');
      let progressText = '';
      if (progress.index > 0) progressText = ' <span class="guide-progress">▶ #' + (progress.index + 1) + '</span>';
      item.innerHTML =
        '<span class="guide-ch">' + ch.ch + '</span>' +
        '<div class="guide-info"><div class="guide-name">' + ch.name + progressText + '</div><div class="guide-desc">' + (ch.desc || '') + '</div></div>' +
        '<span class="guide-cat">' + ch.cat + '</span>';
      item.onclick = () => { tuneToChannel(i); toggleGuide(); };
      list.appendChild(item);
    });
  }

  function updateGuideActive() {
    document.querySelectorAll('.guide-item').forEach(el => {
      const chNum = parseInt(el.querySelector('.guide-ch').textContent, 10);
      el.classList.toggle('active', channels[currentIndex] && chNum === channels[currentIndex].ch);
    });
  }

  function toggleGuide() {
    guideOpen = !guideOpen;
    guide.classList.toggle('hidden', !guideOpen);
    if (guideOpen) {
      buildGuide();
      setTimeout(() => {
        const active = guide.querySelector('.guide-item.active');
        if (active) active.scrollIntoView({ block: 'center', behavior: 'smooth' });
      }, 100);
    }
  }

  document.querySelectorAll('.filter-btn').forEach(btn => {
    btn.onclick = () => {
      document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      activeFilter = btn.dataset.cat;
      buildGuide();
    };
  });

  $('guide-close').onclick = toggleGuide;
  $('btn-ch-up').onclick = prevChannel;
  $('btn-ch-down').onclick = nextChannel;
  $('btn-guide-toggle').onclick = toggleGuide;
  $('btn-shuffle').onclick = toggleShuffle;
  $('btn-mute').onclick = () => {
    if (!ytPlayer) return;
    if (ytPlayer.isMuted()) { ytPlayer.unMute(); $('btn-mute').textContent = 'MUTE'; }
    else { ytPlayer.mute(); $('btn-mute').textContent = 'UNMUTE'; }
  };

  // --- Keyboard ---
  document.addEventListener('keydown', e => {
    if (guideOpen && e.key === 'Escape') { toggleGuide(); return; }
    if (guideOpen) return;
    switch (e.key) {
      case 'ArrowUp': case 'k': e.preventDefault(); prevChannel(); break;
      case 'ArrowDown': case 'j': e.preventDefault(); nextChannel(); break;
      case 'g': case 'G': toggleGuide(); break;
      case 's': case 'S': toggleShuffle(); break;
      case 'm': case 'M':
        if (!ytPlayer) break;
        if (ytPlayer.isMuted()) { ytPlayer.unMute(); $('btn-mute').textContent = 'MUTE'; }
        else { ytPlayer.mute(); $('btn-mute').textContent = 'UNMUTE'; }
        break;
      case 'f': case 'F':
        if (document.fullscreenElement) document.exitFullscreen();
        else document.documentElement.requestFullscreen();
        break;
      case ' ':
        e.preventDefault();
        if (!ytPlayer) break;
        const state = ytPlayer.getPlayerState();
        if (state === YT.PlayerState.PLAYING) ytPlayer.pauseVideo();
        else ytPlayer.playVideo();
        break;
      case 'n': case 'N':
        if (ytPlayer) ytPlayer.nextVideo();
        break;
      default:
        if (e.key >= '0' && e.key <= '9') handleNumber(e.key);
    }
  });

  // --- Touch swipe ---
  let touchStartY = 0;
  document.addEventListener('touchstart', e => { touchStartY = e.touches[0].clientY; }, { passive: true });
  document.addEventListener('touchend', e => {
    const diff = touchStartY - e.changedTouches[0].clientY;
    if (Math.abs(diff) > 60) { diff > 0 ? nextChannel() : prevChannel(); }
  }, { passive: true });
})();
